version: '3'

networks:
  easywrite-network:
    driver: bridge

services:
  mariadb:
    image: mariadb:latest
    container_name: easywrite-service-mariadb
    restart: always
    ports:
      - "3066:3306"
    environment:
      MYSQL_DATABASE: easywrite
      MYSQL_USER: easywrite
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - ./mariadb_data:/var/lib/mysql
    networks:
      - easywrite-network

  redis:
    container_name: easywrite-service-redis
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - ./redis_data:/data
    networks:
      - easywrite-network

# web panel see http://localhost:19001/, password: minio_config/access_key and minio_config/secret_key
#  minio:
#    container_name: minio
#    image: minio/minio:latest
#    restart: always
#    ports:
#      - "19000:9000"
#      - "19001:9001"
#    volumes:
#      - ./minio_data:/data
#    environment:
#      - MINIO_ACCESS_KEY_FILE=/run/secrets/access_key
#      - MINIO_SECRET_KEY_FILE=/run/secrets/secret_key
#      - CONSOLE_SUBPATH=/
#      - MINIO_BROWSER_REDIRECT_URL=http://localhost:19000
#    command: [ "server", "/data", "--console-address", ":9001"]
#    secrets:
#      - access_key
#      - secret_key

#secrets:
#  access_key:
#    file: ./minio_config/access_key
#  secret_key:
#    file: ./minio_config/secret_key

