version: '3'

services:
  easywrite-service:
    image: easywrite-service
    container_name: easywrite-service
    restart: always
    environment:
      SET_CONTAINER_TIMEZONE: "true"
      CONTAINER_TIMEZONE: Asia/Shanghai
      TZ: Asia/Shanghai
    ports:
      - "10010:10010"
    volumes:
      - ./service_config.json5:/etc/config/service_config.json5
      - ./upload:/easy-write/upload
    depends_on:
      - mariadb
      - redis

  mariadb:
    image: mariadb:latest
    container_name: easywrite-service-mariadb
    restart: always
    #    ports:
    #      - "33066:3306"
    environment:
      MYSQL_DATABASE: easy-write
      MYSQL_USER: easy-write
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - ./mariadb_data:/var/lib/mysql

  redis:
    container_name: easywrite-service-redis
    image: redis:latest
    restart: always
    volumes:
      - ./redis_data:/data

