name: Docker Build and Push
# DOCKER_USERNAME
# DOCKER_PASSWORD
# DOCKER_REGISTRY_URL
# 请注意：DOCKER_REGISTRY_URL secret 必须只包含注册表地址，不要包含协议部分，例如应设置为 xxx.xxx.com/xxx，而不是 https://xxx.xxx.com/xxx

on:
  push:
    tags:
      - "*"
  workflow_dispatch:
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get Git Tag
        id: get_tag
        run: echo "TAG=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV

      - name: Build and Push Docker image with version tag and latest
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            AloneDuck/easywrite-service:latest
