name: Docker Build and Push
# DOCKER_USERNAME
# DOCKER_PASSWORD
# DOCKER_REGISTRY_URL

on:
  push:
    tags:
      - "*"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Registry
        uses: docker/login-action@v2
        with:
          registry: nrt.vultrcr.com/wilinz
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get Git Tag
        id: get_tag
        run: |
          # Retrieve the latest Git tag and remove newlines
          TAG=$(git describe --tags --abbrev=0 | tr -d '\n')
          # Sanitize: replace any invalid character with a hyphen
          TAG=$(echo $TAG | tr -c 'a-zA-Z0-9._-' '-')
          # Remove trailing hyphen if present
          TAG=${TAG%-}
          echo "TAG=$TAG" >> $GITHUB_ENV
          echo "Using TAG: $TAG"

      - name: Build and Push Docker image
        run: |
          docker buildx build --platform linux/amd64 \
            -t ${{ secrets.DOCKER_REGISTRY_URL }}/easywrite-service:$TAG \
            -t ${{ secrets.DOCKER_REGISTRY_URL }}/easywrite-service:latest \
            --push -f docker/Dockerfile .
