name: Docker Build and Push
# DOCKER_USERNAME
# DOCKER_PASSWORD
# DOCKER_REGISTRY_URL

on:
  push:
    tags:
      - "*"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Registry
        uses: docker/login-action@v2
        with:
          registry: nrt.vultrcr.com/wilinz
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get Git Tag
        id: get_tag
        run: echo "TAG=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV

      - name: Build Docker image with version tag
        run: |
          docker buildx build --platform linux/amd64 -t ${{ secrets.DOCKER_REGISTRY_URL }}/easywrite-service:$TAG -f docker/Dockerfile .

      - name: Tag Docker image as latest
        run: |
          docker tag ${{ secrets.DOCKER_REGISTRY_URL }}/easywrite-service:$TAG ${{ secrets.DOCKER_REGISTRY_URL }}/easywrite-service:latest

      - name: Push Docker images
        run: |
          docker push ${{ secrets.DOCKER_REGISTRY_URL }}/easywrite-service:$TAG
          docker push ${{ secrets.DOCKER_REGISTRY_URL }}/easywrite-service:latest